import type { Metadata } from "next";
import { Inter, Neuton } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const neuton = Neuton({
  subsets: ["latin"],
  weight: ["400", "700", "200", "300", "800"],
  variable: "--font-neuton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${neuton.variable} font-neuton `}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
